GET http://localhost:8000/auth/user/profile  
GET http://localhost:8000/auth/user/login  
GET http://localhost:8000/auth/user/logout  

GET http://localhost:8000/  
GET http://localhost:8000/auth/user/  

